
device: cpu
target_column: "churn"
training:
  num_epochs: 20
  n_trials: 10
  random_state: 42
  num_splits_cv: 5

optuna:
  n_layers:
    min: 1
    max: 2
  n_units:
    min: 32
    max: 256
    step: 32
  dropout_rate:
    min: 0.1
    max: 0.5
  learning_rate:
    min: 0.00001
    max: 0.01
  batch_size: [16, 32, 64, 128]
  impute_strategy: ["median", "mean", "most_frequent"]

paths:
  logs: src/models/tuning/logs/optuna_tuning.log

logging:
  log_path: "src/data_pipeline/logs/train_nn.log"
  log_level: "INFO"
