name: Deploy to Azure VM
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }} 
          script: |
            cd /home/${{ secrets.AZURE_USER }}/churn-predictor || \
              git clone https://github.com/Jordan-buwa/churn-predictor.git churn-predictor
            cd churn-predictor
            git pull origin main


            # --- CREATE .env FILE ---
            cat <<EOF > .env
            POSTGRES_PORT=${{secrets.POSTGRES_PORT}}
            POSTGRES_HOST=${{secrets.POSTGRES_HOST}}
            POSTGRES_DB_NAME=${{secrets.POSTGRES_DB_NAME}}
            POSTGRES_DB_USER=${{ secrets.POSTGRES_DB_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}
            API_KEY_SECRET=${{ secrets.API_KEY_SECRET }}
            EOF

            # Stop old containers
            docker compose down --remove-orphans || true

            # Build and start
            docker compose build --no-cache
            docker compose up -d

            # Clean up old images/containers
            docker system prune -af --volumes